# Generated by Django 3.1.3 on 2020-11-08 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
